services:
  ros_turtle:
    build: ./src/turtle_sim/
    command: ros2 run turtlesim turtlesim_node
    network_mode: host
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - ./src:/home/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix  
  
  rqt:
    build: ./src/turtle_sim/
    command: rqt
    network_mode: host
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - ./src:/home/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix