services:
  ros_capra_talker:
    build: ./src/capra_talker/
    command: ros2 pkg list
    volumes:
      - ./src:/ros2_ws/src

  ros_capra_listener:
    build: ./src/capra_listener/
    command: ros2 pkg list
    volumes:
      - ./src:/ros2_ws/src