services:
  ros_nanosaur_simulation:
    build: ./src/gazebo_sim/
    command: gazebo
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - ./src:/home/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host