services:
  ros_capra_talker:
    build: ./src/capra_talker/
    command: ros2 run demo_nodes_cpp talker
    volumes:
      - ./src/capra_talker:/ros2_ws/src/capra_talker

  ros_capra_listener:
    build: ./src/capra_listener/
    command: ros2 run demo_nodes_cpp listener
    volumes:
      - ./src/capra_listener:/ros2_ws/src/capra_listener