services:
  ros_nanosaur_simulation:
    build: ./src/turtle_sim/
    command: ros2 run turtlesim turtlesim_node
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - ./src:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host